Scille/umongo

tests/test_fields.py, umongo/embedded_document.py
=> Add schema arg to EmbeddedDocumentImplementation dump method

umongo/embedded_document.py
Closes https://github.com/Scille/umongo/issues/28.
=> EmbeddedDocument raises AttributeError if get/set/deleting non existing field

tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, tests/frameworks/test_txmongo.py, tests/test_document.py, umongo/data_proxy.py, umongo/document.py
I would like to be able to tell if a Document was modified.
Was there a simpler / more recommended way?
I suppose we could also use 
if self._data._to_mongo_update() is not None
but it takes more computations.
I could add tests if you're interested.
=> Add is_modified method to Document

AUTHORS.rst
Now that I introduced a few bugs, I suppose I should get my share of the blame...
=> Add myself to AUTHORS.rst

tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, tests/frameworks/test_txmongo.py, umongo/data_objects.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py, umongo/frameworks/txmongo.py
Fixes https://github.com/Scille/umongo/issues/91.
(BTW, it looks like the `no_data` parameter has no effect. Is this a TODO?)
=> Add force_reload to *Reference.fetch

umongo/embedded_document.py
Looks like this is never use. `is_modified` only checks the data proxy.
=> Remove EmbeddedDocument._modified

tests/test_embedded_document.py, umongo/embedded_document.py
Same as https://github.com/Scille/umongo/pull/109 but for `EmbeddedDocument`.
=> Fix deletion of field proxied by a property in EmbeddedDocument

tox.ini
=> Fix flake8 config in tox.ini

tests/test_marshmallow.py, umongo/fields.py
Fixes #64
Same as https://github.com/Scille/umongo/pull/102. Pushing as new PR for clarity.
=> Fix ListField.as_marshmallow_field: pass params to container

tests/test_marshmallow.py, umongo/abstract.py, umongo/fields.py
Closes #65 
Same as https://github.com/Scille/umongo/pull/103. Pushing as new PR for clarity.
=> Pass meta attributes to Schema in as_marshmallow_schema

tox.ini
https://github.com/pytest-dev/pytest-twisted/pull/45
=> Hold pytest version until pytest-twisted fix is released

tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, tests/frameworks/test_txmongo.py, umongo/frameworks/tools.py
=> Fix cook_find_filter bug when filtering by _id on a document subclass

AUTHORS.rst, tests/test_data_proxy.py, tests/test_embedded_document.py, tests/test_fields.py, umongo/fields.py
=> Add Decimal128 support

HISTORY.rst, docs/userguide.rst, tests/test_data_proxy.py, tests/test_document.py, tests/test_inheritance.py, tests/test_marshmallow.py, umongo/__init__.py, umongo/abstract.py, umongo/data_proxy.py, umongo/fields.py, umongo/schema.py
=> Rework default/missing attributes behavior

HISTORY.rst, tests/test_marshmallow.py, umongo/abstract.py
=> Rework extract marshmallow field params

.travis.yml, CONTRIBUTING.rst, setup.py, tox.ini
=> Drop Python 3.4

.travis.yml, CONTRIBUTING.rst, setup.py, tox.ini
=> Support Python 3.7

tests/test_fields.py, umongo/fields.py
=> Fix millisecond overflow issue in StrictDateTimeField

.travis.yml, setup.py, tox.ini
=> Test against Python 3.8

docs/userguide.rst, examples/flask/app.py, examples/klein/app.py, examples/muffin/app.py, setup.py, tests/test_data_proxy.py, tests/test_document.py, tests/test_embedded_document.py, tests/test_fields.py, tests/test_marshmallow.py, umongo/abstract.py, umongo/builder.py, umongo/data_objects.py, umongo/data_proxy.py, umongo/fields.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py, umongo/frameworks/txmongo.py, umongo/marshmallow_bonus.py, umongo/query_mapper.py
Closes https://github.com/Scille/umongo/issues/129.
The failing test is due to an issue in marshmallow that was fixed since 3.0.0rc1 was released. It'll be fixed with next marshmallow release.
=> Marshmallow 3 compatibility

umongo/abstract.py
See https://github.com/Scille/umongo/pull/154#issuecomment-605454722.
=> Grab all marshmallow_-prefixed args when generating marshmallow Schema

tests/test_fields.py, umongo/fields.py
=> Fix DictField/ListField default

umongo/abstract.py, umongo/fields.py
=> Remove unused translate_query

umongo/abstract.py
=> Fix BaseField.__repr__

.travis.yml, setup.py, tests/frameworks/test_motor_asyncio.py, tox.ini
=> Drop Python 3.5

tests/test_data_proxy.py, umongo/builder.py, umongo/data_proxy.py, umongo/document.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py, umongo/frameworks/txmongo.py, umongo/schema.py
=> Remove BaseDataProxy.*_by_mongo_name methods

tests/test_embedded_document.py, umongo/builder.py, umongo/embedded_document.py, umongo/fields.py
Closes #86.
Rebase of @touilleMan's branch.
=> Rework abstract EmbeddedDocument policy to match Document

tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, tests/frameworks/test_txmongo.py, umongo/abstract.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py, umongo/frameworks/txmongo.py
=> Replace RuntimeError with umongo exceptions

tests/test_document.py, tests/test_embedded_document.py, umongo/builder.py, umongo/document.py, umongo/embedded_document.py, umongo/instance.py
Factorize code duplicated in Document and EmbeddedDocument.
=> Factorize Document and EmbeddedDocument

AUTHORS.rst, tests/frameworks/test_motor_asyncio.py, umongo/frameworks/motor_asyncio.py
=> Fix motor 2.2.0 compat

.travis.yml, CONTRIBUTING.rst, setup.py, tox.ini
=> Drop Python 3.6

README.rst, azure-pipelines.yml, umongo/fields.py
=> Support only MongoDB 4.2+

tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py
Closes #224.
Allows to use transaction management from pymongo and motor.
```py
with instance.session() as session:
with session.start_transaction():
doc = Doc(s='test')
doc.commit()
doc_id = doc.id
ret = Doc.find_one(doc_id)
assert ret.s == doc.s
```
=> Add session context var to PyMongoInstance and MotorAsyncIOInstance

tests/test_fields.py
=> Test embedded document refering self as string

umongo/fields.py
Fix passing metadata (overlooked in #328).
Rename variables.
Remove overrides that don't seem useful.
Fix I18n of generated ma fields.
=> Fix/rework as_marshmallow_schema in umongo fields

tests/conftest.py, tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, tests/frameworks/test_txmongo.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py, umongo/frameworks/txmongo.py
=> Fix io_validation for None reference

HISTORY.rst, docs/apireference.rst, docs/userguide.rst, tests/test_document.py, tests/test_embedded_document.py
- Actually, inheritance order doesn't matter.
- Document feature.
=> Review and document mixin feature

tests/test_document.py, umongo/embedded_document.py
I may be misremembering, but I thought this worked at some point in the past.
=> Add fields to EmbeddedDocument.__dir__() to facilitate dynamic code completion

.github/workflows/build-release.yml, pyproject.toml, tox.ini
Let's require marshmallow 4 while we're at it.
=> Drop marshmallow 3

examples/flask/testbed.py, examples/inheritance/app.py, pyproject.toml, tests/common.py, tests/frameworks/test_motor_asyncio.py, tests/frameworks/test_pymongo.py, tests/frameworks/test_txmongo.py, tests/test_indexes.py, umongo/abstract.py, umongo/builder.py, umongo/data_objects.py, umongo/data_proxy.py, umongo/document.py, umongo/embedded_document.py, umongo/fields.py, umongo/frameworks/__init__.py, umongo/frameworks/motor_asyncio.py, umongo/frameworks/pymongo.py, umongo/frameworks/txmongo.py, umongo/instance.py, umongo/mixin.py, umongo/template.py
- Enable B026. Remove *args from `find_one` signature as it doesn't play well with `projection` passed as kwarg.
- Enable INT001
- Enable UP031
=> Ruff fixes
