Scille/umongo

tests/test_data_proxy.py
tests/test_fields.py
umongo/data_proxy.py

I'm having issues unsetting fields. It it likely I misunderstood the whole thing, but from what I understand, `_to_mongo_update` generates `$unset` operations as (see [here](https://github.com/Scille/umongo/blob/master/tests/test_data_proxy.py#L131) for instance):
{'$unset': ['a', 'b']}
This generates errors:
"Modifiers operate on fields but we found a Array instead. For example: {$mod: {<field>: ...}} not {$unset: [ \"a\", \"b\" ]}"
Indeed, the [docs](https://docs.mongodb.com/manual/reference/operator/update/unset/) indicate the expected syntax is:
$unset: { quantity: "", instock: "" }
I'm a bit surprised no one ever hit this before, which makes me think I might be wrong.
Anyway, here's a fix proposal to illustrate the idea. Obviously, it breaks the tests. I'd rather you validate the …

Fix $unset syntax in `_to_mongo_update`

---

umongo/fields.py

I stumbled upon this while trying to use a Schema to serialize a Document using
schema.dump(document)
(That use case we'd like to support but currently don't really.)
I'm not sure this can happen in the supported use case (use of Schema to serialize data_proxy)
document.dump()
but I saw the same mechanism in `ObjectIdField` and in most if not all Marshmallow fields.
I assume it can't hurt...

fields: _serialize to None if value is None

---

tests/frameworks/test_pymongo.py
umongo/frameworks/pymongo.py

This allows slicing umongo's PyMongo WrappedCursor like you would slice a PyMongo Cursor.
```py
cursor = Student.find()
for elem in cursor[2:5]:
...
```

Fix PyMongo WrappedCursor slicing

---

tests/test_fields.py
umongo/document.py
umongo/embedded_document.py

This update method is copied from Document, except it calls `self.set_modified` to mark the embedded document as modified.
I also removed the `return` statements in both EmbeddedDocument and Document update methods, as I didn't see the point, but maybe this is wrong.
I also added tests to the new update methods.
Happy to rework this if you have comments.

Add update method to EmbeddedDocument

---

tests/test_fields.py
tests/test_marshmallow.py

Looks like some `assert` statements are missing.
This commit also fixes a typo and removes unused imports.
Note that this fix spots an issue in `DictField` (or in the test).

Fix missing "assert" statements in tests

---

tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
umongo/document.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py

Trying to address https://github.com/Scille/umongo/issues/35.
Incidentally, in motor_asyncio, `pre_delete` is now executed only if doc is created, like on the other frameworks.
Also added possibility for `pre_delete` to add additional query filters, like `pre_update`.

 Add `conditions` to delete method

---

tests/test_data_proxy.py
umongo/data_proxy.py

I may be mistaken, but the way I understand the code, `self.not_loaded_fields` is not reset when loading non-partial, so if a partial load was performed previously, it still has fields missing from this previous load.

DataProxy: Empty not_loaded_fields on non-partial loads

---

tests/test_data_proxy.py
umongo/data_proxy.py

Current implementation of `DataProxy.set()` does not allow setting `None` in a field with `allow_none = True` and validators defined, because it calls validation on the value even if it is `None`.
In Marshmallow, the validators are not called in this case (see https://github.com/marshmallow-code/marshmallow/blob/e6ddef938b3b274a4965cad344c3864e643e6baa/marshmallow/fields.py#L254).
My explanation sucks, but hopefully, the tests will speak for themselves...

DataProxy.set(): don't call validation if allow_none = True and value is None

---

tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
tests/test_data_proxy.py
umongo/abstract.py
umongo/fields.py

Please tell me what you think about this.
Currently, required fields validation fails if an embedded document with required fields is missing, even if the embedded document itself is not required.
I think this should fail only if the embedded document itself is required.
Consider this model:
```
User
- name (string, required)
Team
- manager (embedded user, not required)
```
manager field in Team is not required. If a manager is provided, it should have a name (required field), but if no manager is provided, I don't think validation should fail. No manager, no problem!
It should fail only 
- if manager is required 
- or if manager is provided without name, whether or not it is required.

Don't fail if missing embedded doc with required fields

---

tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py

Looks like there's a `self.required_validate()` missing in `commit` (all drivers) when updating a document.
Fix and tests in the PR.
The first commit added tests about embedded field and list of embedded fields which is unnecessary to test this particular issue, so I "simplified them out". I left them in a separate commit so that they're easy to grab if you find them useful anyway.

Fix required check on update

---

tests/test_marshmallow.py
umongo/abstract.py

Sometimes, it is useful to pass a field arbitrary names attributes that are used in the application. Marshmallow supports this and stores those attributes in `Field.metadata`.
For instance, when using Marshmallow + apispec, [API specific parameters](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L165) can be passed to the `Schema` when declaring the model.
It would be nice to be able to declare those attributes in each uMongo `Field`. It looks as easy as just passing the `metadata` as kwargs when creating the Marshmallow field.
I don't see any drawback to this, except it may pass metadata that was there for uMongo purposes and wasn't meant to trickle down to Marshmallow, but I think Marshmallow will just silently ignore it, this shouldn't be a …

Let as_marshmallow_field pass metadata

---

tests/test_fields.py
umongo/fields.py
umongo/marshmallow_bonus.py

There was an issue in `StrictDateTime`. I wrote
```py
date.astimezone(tzutc())
```
which does nothing because astimezone does not modify `date` (a datetime is immutable anyway).
I changed it into
```py
date = date.astimezone(tzutc())
```
This commit also adds corresponding tests.
Note that I manage the case where we get datetimes from Mongo that are aware and not UTC. This is currently not possible with PyMongo and I doubt it will change anytime soon. I didn't check the other drivers and I guess it is the same there, so we could safely remove those two lines: https://github.com/Nobatek/umongo/blob/fix_strictdatetime_issue/umongo/fields.py#L227-L228.

Fix StrictDateTime issue when using aware datetime as input

---

umongo/marshmallow_bonus.py

None is invalid unless allow_none is True, which is handled in Field's deserialize method.

Don't deal with None case in Marshmallow bonus fields _deserialize method

---

tests/test_data_proxy.py
umongo/data_proxy.py

My [earlier modifications to `set`](https://github.com/Scille/umongo/pull/63) left uncovered cases.
In marshmallow, the case where value is None and field.allow_none is False is managed in [`_validate_missing`](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L229), which we skip. So we need to do that ourselves here.
Without this fix,
- we call `_deserialize` on any data, even None, which yields ValidationError on legit inputs
- ValidationError when value is None and allow_None is False does not return the ['null'] message

Fix allow none in DataProxy.set

---

tests/test_data_proxy.py
tests/test_embedded_document.py
umongo/data_proxy.py
umongo/embedded_document.py

I've been having issues when comparing `EmbeddedDocument`s with nesting.
Sometimes, the nested field is not an `EmbeddedDocument` but `missing` or `None`, and the comparison fails raising `AttributeError` because `other._data` does not exist.
I tried to cover theses cases and maybe I'm covering a bit larger, but I don't think it should be an issue.

Fix equality tests

---

HISTORY.rst
umongo/fields.py
umongo/marshmallow_bonus.py

This commit
- factorizes the TZ awareness enforcement logic (I wonder why I didn't do that right away...)
- makes `StrictDateTime` bonus field reject `datetime.datetime` instances, which is coherent with `DateTime`. Accepting `datetime.datetime` instances is done in umongo's `StrictDateTimeField` only, just like with `DateTimeField`.
Should I had test for this?

Rework StrictDateTime

---

tests/test_document.py
umongo/document.py

Like `__setattr__`, `__delattr__` should only get to the DataProxy for fields, not other attributes. Otherwise, when a field is proxied by a property, its deletion fails.

Fix deletion of field proxied by a property

---

tests/test_fields.py
umongo/fields.py

I had a helluva time debugging this one...
Assume you have a `ReferenceField` in an `EmbeddedDocument`. Now try to change the value of the embedded document in the document, like this:
my_doc.embedded_doc = new_embedded_doc
You get into troubles, with a messed up reference field.
The issue here is related to the use of `_deserialize_from_mongo` as you explain [in this comment](https://github.com/Scille/umongo/pull/84#issuecomment-268840412).
Since `EmbeddedField._deserialize` calls `_deserialize_from_mongo`, we end up calling `deserialize_from_mongo` on the reference field with data that is already deserialized, so we pass that deserialization method a `Reference` while it expects an `ObjectID` (or a string representation of an `ObjectId`).
Since `Reference.__init__()` does not check its …

Fix ReferenceField in EmbeddedDocument assignment

---

HISTORY.rst
tests/test_embedded_document.py
tests/test_fields.py
umongo/abstract.py

I'm afraid there's an issue with `allow_none` fields.
For both serialization and deserialization to/from Mongo, if the value is None, None should be returned and all `_(de)serialize_from_mongo` overridden methods should be skipped, as they don't deal with the `allow_none` case and either break (e.g. StrictDateTime) or return a nullish object (empty list, empty dict).
See attached fix proposal.
I didn't code any test as I'm in a bit of a rush and I'd rather have your feedback first.

Fix allow_none fields [de|]serialization

---

.travis.yml

The same workaround was applied to marshmallow: https://github.com/marshmallow-code/marshmallow/commit/6aba50cf109b7c39c9e3e6631911f1892418898b.

Fix Py34 Travis tests

---

examples/flask/app.py

- fixes `TypeError: as_marshmallow_schema() missing 1 required positional argument: 'self'`

fix error due to typo in flask example

---

examples/flask/app.py

fixes `TypeError: 'MarshmallowUserSchema' object is not callable`

fix flask example

---

README.rst

Update the quick example docs adding the `ensure_indexes` in order to respect the email unique constraint.

Update the quick examples docs closing #135

---

setup.cfg
tests/frameworks/test_mongomock.py
tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
tests/test_instance.py

- Update flake8 config to ignore W504 (see rationale in https://github.com/marshmallow-code/apispec/pull/322).
- Don't call fixtures directly, which is forbidden with pytest 4.
- Don't test index version. The index version depends on the database version (and configuration). It should not be tested here. This breaks the CI tests as they are now run on MongoDB 3.4 which default to v2.

Fix CI tests

---

requirements_dev.txt
setup.py
tests/common.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
tox.ini

pymongo should be a hard dependency because bson is imported in the main code.
Also, there is no need to test the version is > 3.2 if 3.2 is required.

Make pymongo a mandatory dependency (it is needed for bson)

---

README.rst
docs/userguide.rst
setup.py
tests/frameworks/test_pymongo.py
umongo/frameworks/pymongo.py

https://api.mongodb.com/python/current/changelog.html
> Deprecated `pymongo.collection.Collection.count()` and `pymongo.cursor.Cursor.count()`. These two methods use the count command and may or may not be accurate, depending on the options used and connected MongoDB topology. Use `count_documents()` instead.
This PR is based on #148.
It adds a `count` method to `PyMongoDocument`. (I named it `count` and not `count_documents` to match umongo's `TxMongoDocument`. I have no objection to naming it `count_documents`.)
I'd do the same for `MotorAsyncIODocument` except it requires motor>=2.0, which is not supported.
Since we already require pymongo 3.x, I figured bumping the requirement wouldn't be too much of an issue and would save us the pain of supporting both 3.7 and 3.6-. I could rework …

Update to pymongo 3.7

---

tests/test_marshmallow.py
umongo/abstract.py
umongo/fields.py

Parameters of `as_marshmallow_schema` should be passed to nested Schemas.
In this implementation, I pass them to all fields, so that `EmbeddedField` gets it and pass it when calling `as_marshmallow_schema`.
Nothing really complicated here. I had to modify `as_marshmallow_field`'s signature, hence the modifications in unrelated fields.
Note that I changed `kwargs` into `field_kwargs` in those fields to make it obvious to the reader it is not the same `kwargs` we're talking about. It would work without the rename, but it would look like a mistake at first sight:
```python
def as_marshmallow_field(self, params=None, mongo_world=False, **kwargs):
kwargs = self._extract_marshmallow_field_params(mongo_world)
```
Another option was to use `_` but I'm not sure it is so common for kwargs: …

Pass as marshmallow schema params to nested schemas

---

umongo/document.py

CI errors are unrelated and addressed in https://github.com/Scille/umongo/pull/155.

Remove useless condition in DocumentImplementation init

---

setup.py
tests/test_document.py
tests/test_embedded_document.py
umongo/document.py
umongo/embedded_document.py

I think the root cause is that when using `deepcopy` (I think this applies to pickle as well but didn't double-check), `hasattr(my_doc, __setstate__)` is called before the object is instantiated and therefore `self._data` does not exist, so we get an infinite recursion in `__getattr__`.
I think it is advised to add a condition like the one in this PR to fix this (inspired by https://stackoverflow.com/a/42272450/4653485).
Note that this prevents the use of attributes with leading and trailing double underscore, but oh well... I'm not sure this should even be considered a breaking change.
(CI errors unrelated and fixed in https://github.com/Scille/umongo/pull/155.)

Fix __getattr__ to deepcopy Document and EmbeddedDocument

---

setup.py
tests/test_document.py
tests/test_embedded_document.py
umongo/document.py
umongo/embedded_document.py

Implements `clone` method proposed in https://github.com/Scille/umongo/issues/83#issuecomment-268842201.
This PR is based on https://github.com/Scille/umongo/pull/157 which fixes DataProxy deepcopy.

Add clone method to Document

---

tests/test_marshmallow.py
umongo/abstract.py

This adds a cache to as_marshmallow_schema.
My use case is the following:
My app calls `as_marshmallow_schema` on all top-level schemas (one schema per resource). Some low-level schemas are used in many places throughout the code, embedded, sometimes deeply, in top-level schemas.
Without this change, the marshmallow schemas generated for those embedded umongo schemas are duplicated. Functionally, it makes no difference, but then they also get duplicated in the auto-generated OpenAPI specification that I generate with apispec, which makes the doc a bit ugly.
This is just one use case, but more generally, it's a pity to duplicate stuff.
The caching mechanism here is two-fold. Hashable parameters are used as a key in the cache dictionary. Dictionary parameters are not hashable, so they can't …

Add Schema cache to as_marshmallow_schema

---

HISTORY.rst
tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
tests/test_fields.py
umongo/fields.py

Closes #105.
Fixes #78.
-  ``DictField`` and ``ListField`` don't default to empty ``Dict``/``List`` (see #105).
-  Serialize empty ``Dict``/``List`` as empty rather than missing (see #105).
-  Fix passing a default value to a ``DictField``/``ListField`` as a raw Python
``dict``/``list`` (see #78).

Rework ListField and DictField

---

tests/test_fields.py
umongo/fields.py

The point of this change is to ensure consistency in the representation of the data before and after storing it to and retrieving it from the DB.
Basically, if the datetime is not rounded when deserialized in the object, the object has more precision than the database can handle. When committing the object in the DB, then fetching it back, precision is lost.
It is more consistent to lose the precision right away.
Real life use case:
REST API, POST request. The resource view function instantiates an object with a datetime with microsecond precision. The object is saved in DB. The view function returns the object. The representation of the object does not match what is stored in DB. A subsequent GET request will return a slightly different object. Things get even worse when ETag comes into …

Round datetimes to milliseconds in DateTimeField and StrictDateTimeField

---

tests/test_document.py
umongo/abstract.py
umongo/fields.py

I changed my mind about https://github.com/Scille/umongo/issues/78#issuecomment-470522732.
This change factorizes default/missing deserialization from `DictField`/`ListField` into `BaseField`.
Then, the `default` values are validated, which fixes the problem described in https://github.com/Scille/umongo/issues/36#issuecomment-247329135.
It is not only about validation. Consider a `DateTimeField` with a default value of `utcnow`. We want it to get the same constraint as if set manually. I'm thinking of the rounding added in https://github.com/Scille/umongo/pull/172.

Validate default values

---

tests/test_fields.py
umongo/fields.py

Forgotten in https://github.com/Scille/umongo/pull/172.

Round datetimes to milliseconds in LocalDateTimeField

---

umongo/frameworks/pymongo.py

`partial` can't be `True`, it is `None` or an iterable.
This is consistent with what is done for txmongo and motor_asyncio.

Simplify "partial" in pymongo._io_validate_data_proxy

---

tests/test_embedded_document.py
tests/test_fields.py
umongo/fields.py

For the reason this was done in the first place, see https://github.com/Scille/umongo/pull/84#issuecomment-268840412.
I just stumbled on a use case where it wouldn't work.
The assumption that deserialization (from outside to OO world) provides what pymongo would return is incorrect when the data is not serialized in DB in its OO world form. This is the case for fields that have custom `_serialize_to_mongo` / `_deserialize_from_mongo` methods.
For instance, if the embedded document contains a `DateField`, the deserialization produces a `datetime.date` and `deserialize_from_mongo` will choke on that because it expects a `datetime.datetime`.
I believe this fix does the right thing.
The only thing that bothers me is that it duplicates the `_schema` string from marshmallow:
```py …
```

Don't call _deserialize_from_mongo in Field._deserialize

---

tests/test_fields.py
umongo/fields.py

Fixes #189.
The second commit introduces an abstract class to factorize the logic. @touilleMan, if you like the first version better, I can remove the second commit.

Fix millisecond overflow when milliseconds round to 1s in DateTimeField

---

tests/test_data_proxy.py
umongo/data_objects.py
umongo/data_proxy.py

Various fixes about `is_modified`:
- Include modified `BaseDataObject`s in `BaseDataProxy.get_modified_fields` and `BaseDataProxy.get_modified_fields_by_mongo_name`. While fixing this, I factorized the logic in `get_modified_fields`. I don't think it is much worse in terms of performance. BTW, there was a type mismatch in those two methods, as the first returned a `list` and the second returned a `set`. Now, both return a `set`. I don't think this qualifies as a breaking change since it is not public API. `BaseDataProxy.get_modified_fields_by_mongo_name` was not even tested.
- Always return a boolean in `List.is_modified`. Previously, it could return `None`.
- `List`: set modified when using `del my_list_field [i]` (Issue reported in …

Fix is_modified

---

tests/test_marshmallow.py
umongo/marshmallow_bonus.py

Marshmallow bonus `Reference` field does not round-trip.
It works if the data is loaded then passed to a `Document` then the document is dumped.
```py
loaded_data = Schema().load(data)
loaded_data['ref']  # ObjectId
doc = Document(**loaded_data)
doc.ref  # Reference
dumped_data = Schema().dump(doc)
dumped_data  # string
```
But it fails if the data is never passed to a document init: the `Reference` field serialization method expects a `Reference` data object, not an `ObjectId`.
```py
data['ref']  # string
loaded_data = Schema().load(data)
loaded_data['ref']  # ObjectId
dumped_data = Schema().dump(loaded_data)  # fails
```
Same with `GenericReference` field.
This PR allows to load then dump references without instantiating an object.

Let Reference and GenericReference round-trip

---

.travis.yml
setup.py
tests/frameworks/test_motor_asyncio.py
tox.ini
umongo/frameworks/motor_asyncio.py

Update API to support v2.0.0 of motor. This involves changing tests
that use the deprecated count() cursor method to use either
count_documents() or to_list() instead, and removing the callback
keyword argument from the to_list wrapper.

Add count_documents support to motor asyncio Documents

---

.travis.yml

Switch to a token that only allows uploading umongo updates to pypi

Update pypi credentials for travis CI

---

tests/test_data_proxy.py
tests/test_fields.py
tests/test_marshmallow.py
umongo/builder.py
umongo/data_objects.py
umongo/fields.py

Use fields for keys/values in DictField

---

tests/test_instance.py
umongo/__init__.py
umongo/exceptions.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py

Closes #203.
- Rework exception.py.
- Replace ReferenceError with a custom umongo error (see #203).
- Expose exceptions meant to be caught in user code in a normal process (like update / delete error and such,...) and not those that should be noticed and fixed by the developer (document definition error,...). The choice is probably arguable but the other exceptions are available in umongo.exceptions anyway.

Rework exceptions

---

tests/test_data_proxy.py
umongo/data_proxy.py

Before this fix, `set_by_mongo_name` would raise but modify the data.

Don't modify data proxy on partial not loaded access

---

tests/test_marshmallow.py
umongo/abstract.py
umongo/builder.py
umongo/document.py
umongo/embedded_document.py
umongo/fields.py

This changes allows to set a base marshmallow schema class in the `Document` / `EmbeddedDocument` template.
It removes the complicated logic used to pass schema parameters (`check_unknown_fields`, `meta`, `params`) along the `as_marshmallow_schema` / `as_marshmallow_field` calls.
The former implementation passing params allows twisted cases like passing a specific parameter to a schema deeply nested in the document when calling `as_marshmallow_schema`, but in a way that is absolutely not practical: it takes a hugs unreadable dict as input.
In real life, schema parameters such as `unknown` are most often the same for all the application, so it makes sense to factorize them in a base schema.
Corner cases can always be addresses with this implementation. It might be a little bit more …

Set MA_BASE_SCHEMA_CLS in Document / EmbeddedDocument

---

tests/test_document.py
tests/test_embedded_document.py
umongo/builder.py

Closes #188.
This PR allows to use Mixin classes in `Document` and `EmbeddedDocument` definition.
It only works if the Mixin is declared first (leftmost) in the `Document` definition.
```py
class MyMixin:
a = fields.IntField()
class MyDoc(MyMixin, Document):  # Mixin first
b = fields.IntField()
```

Support mixins in (Embedded)Document definition

---

docs/userguide.rst
examples/inheritance/app.py
tests/conftest.py
tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
tests/test_document.py
tests/test_embedded_document.py
tests/test_indexes.py
tests/test_inheritance.py
tests/test_marshmallow.py
umongo/builder.py
umongo/document.py
umongo/embedded_document.py

This feature behaves differently on `Document` and `EmbeddedDocument`.
As I was about to make both consistent, I realized that I didn't really see the point of the feature. It seems to only serve the purpose of triggering an exception if someone tries to inherit a document class that was not meant to. It has no influence on the `cls` field.
Let's assume we know what we're doing and, rather than default to `allow_inheritance=True` for `Document` to match `EmbeddedDocument`, remove the feature.

Remove allow_inheritance

---

AUTHORS.rst
tests/test_fields.py
umongo/data_proxy.py
umongo/fields.py

Fix required_validate with allow_none fields

---

umongo/instance.py

This feature is broken.
- If as_attribute is False, the check performed to raise `AlreadyRegisteredDocumentError` is screwed.
- There could be name clashes between different doc types (document, embedded, mixin).
Removing it solves the name clash issue. It means the user can not access a document as `instance.MyDocument` anymore but it is not that bad.

Remove as_attribute argument of register method

---

docs/userguide.rst
tests/test_document.py
tests/test_embedded_document.py
tests/test_marshmallow.py
umongo/__init__.py
umongo/embedded_document.py
umongo/expose_missing.py
umongo/schema.py

- Use Python 3.7's context variable feature to create a context manager in which a document returns missing for missing data rather than None
- Use this context manager in schema_from_umongo_get_attribute
This makes the Document responsible for outputing missing rather than the schema having to guess. Also the schema works with any type of data, not only a Document instance (with other data, the context manger is no-op).
I hoped to remove the whole `mongo_world` management thanks to this, but there are other issues with data from Mongo vs. Document.
The benefit is not as great as I expected, but I still like this implementation.

Add ExposeMissing context manager

---

tests/test_marshmallow.py
umongo/abstract.py
umongo/fields.py
umongo/marshmallow_bonus.py
umongo/schema.py

Follows  #261.
Removing this parameter simplifies the implementation.
I don't see the use for this feature. Once we have the `ExposeMissing` context manager from #261, it only serves the purpose of allowing a user to use a schema between the outside world and the database, shortcutting the ODM layer. I don't see the point of this, and I don't think it is worth the complexity, so let's simplify things.

Remove mongo world

---

tests/test_query_mapper.py
umongo/query_mapper.py

Document is considered a reference and the pk is passed.
EmbeddedDocument is dumped in the query.

Allow passing Document and EmbeddedDocument in queries

---

tests/test_document.py
tests/test_embedded_document.py
umongo/builder.py
umongo/data_proxy.py
umongo/document.py
umongo/embedded_document.py

`_fields` is computed once on class creation rather than on first access
Allows setting arbitrary attributes on objects
----------------------
My first intent here was to fix an issue with fields from mixin classes. It appears the problem is more complicated than this (#271) so I'm not sure this change is worth it.
I don't really see the point of forbidding setting arbitrary attributes, so I'm still fine with this change. But I don't mind keeping things as they are as well.
I like the idea of setting the list at class creation time rather than on access, but I guess it could be achieved with real_attributes as well to keep current behaviour.
Note: See if to_raise argument in data proxy methods still has a meaning.

Replace (Embedded)Document.real_attributes with _fields

---

umongo/builder.py

No need to do this here because it is done when registering the `EmbeddedDocument`.
Solvers the first issue in #79.

Don't call patch_field on EmbeddedField schema fields

---

umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py

Use structured info rather than parse error message.
No need to iterate over indexes. (This change could be a step towards solving #79.)

Use structured error info from DuplicateKeyError

---

tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py

This should not be useful in everyday use. But it may come in handy for maintenance tasks, to rewrite documents from scratch:
- Fix document broken by another tool
- Write migration tool

Add replace argument to commit method

---

docs/apireference.rst
tests/common.py
tests/conftest.py
tests/test_builder.py
tests/test_instance.py
umongo/__init__.py
umongo/exceptions.py
umongo/frameworks/__init__.py
umongo/frameworks/mongomock.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py
umongo/instance.py

Remove `templates` argument to `BaseInstance` (undocumented and untested).
Merge `BaseInstance`, `Instance` and `LazyLoaderInstance` into `Instance`.
Make `Instance` an abstract base class.
Rename `Instance.init` into `Instance.set_db`.
Don't expose framework instances in `umongo` top module. They must be imported from `umongo.frameworks`.
Before this change, one could use `Instance(db)` and get the right builder class, but not the right instance class, which works fine because there is no specific method in each framework instance class (for now).
After this change, one must pick a specific framework instance or explicitly call the factory method `Instance.from_db`.
The use case of registering documents then setting the db didn't work before the change because one would either call …

Rework instance

---

tests/common.py
umongo/instance.py

Fixes an issue introduced in #314 preventing from doing
```py
instance = PyMongoInstance(db)
```
Only lazy registration would work
```py
instance = PyMongoInstance()
instance.set_db(db)
```
Modifies a test config to use the first form, as a non-reg test.

Fix instance init with db as parameter

---

docs/index.rst
docs/migration.rst
tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/tools.py
umongo/frameworks/txmongo.py

umogo 3 introduces a change in the way embedded documents are represented in database.
This PR provides instance subclasses that can help a user migrating his DB.
The process is not really automatic, but at least this class is useful to build a simple migration script.
Note that it requires access to the model (umongo classes). In other words, the easiest migration path would be to branch the application code to plug this instance in place of the usual one, call the migration method, then end the application.

Add migration instance classes

---

tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_txmongo.py

Closes #183.
Querying using a field only defined in a subclass is not something that should be encouraged because the query mapper can't do its job, leaving the user with a raw mongo query which can be unexpected.
It works, but let's not show it in the tests.

Fix tests: don't query with field from child class

---

docs/userguide.rst
tests/test_embedded_document.py
tests/test_fields.py
tests/test_indexes.py
umongo/builder.py
umongo/document.py
umongo/fields.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/txmongo.py
umongo/instance.py

Closes #79.
Ensure embedded document resolution in `EmbeddedField` occurs lazily so that embedded document can be passed as string.
`indexes` become a `Document` cached class property and should now be accessed as `Doc.indexes` rather than `Doc.opts.indexes`.
A downside of this is that using an unregistered embedded document will only be caught on use and not on document registration, in other words at application runtime rather than init.

Postpone embedded document resolution

---

umongo/abstract.py
umongo/document.py
umongo/embedded_document.py
umongo/mixin.py
umongo/template.py

Centralize the `MA_BASE_SCHEMA_CLS` in template rather than scattering it in `Document`, `EmbededdDocument` and `Mixin`.
The `MA_BASE_SCHEMA_CLS` class attribute in `BaseSchema` is not used because it is overridden by the builder. I added a comment to hint the user not to override it here but in template classes.

Centralize MA_BASE_SCHEMA_CLS in Template

---

tests/common.py
tests/test_data_proxy.py
tests/test_embedded_document.py
tests/test_marshmallow.py
tests/test_query_mapper.py
umongo/abstract.py
umongo/data_proxy.py
umongo/template.py

Closes #55. Fixes broken embedded document query.
Might introduce a performance penalty.
We could make the base class customizable and this opt-in but
- it would add complexity
- the embedded doc query would still be broken by default
We could make the base class customizable and this opt-out but
- it would add complexity
- people with a real will against this (because of the perf penalty and because they don't query on embedded docs) can monkey-patch the base class.

Make BaseSchema ordered

---

tests/test_marshmallow.py
umongo/abstract.py

This makes a sensible default IMHO.
Can be opted out by subclassing base marshmallow schema.

Add "remove missing" feature to base marshmallow schema 

---

umongo/document.py
umongo/instance.py

Addresses #365 
Now it just checks if the `db` is `None`.
Perhaps there are some edge cases with other database types which _do_ implement `bool`?
If so, we can move this change down to the `PyMongoInstance` subclass, but it would require a little more rework.

Fix issue where pymongo Database raises if bool'd

---

tests/conftest.py
tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_pymongo.py
tests/frameworks/test_tools.py
tests/frameworks/test_txmongo.py
umongo/data_objects.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/pymongo.py
umongo/frameworks/tools.py
umongo/frameworks/txmongo.py
umongo/query_mapper.py

Adds projection argument to `Reference.fetch()`, allowing partial reference documents to be returned.
Addresses _half_ of issue #196

Add projection argument to Reference.fetch()

---

.github/workflows/build-release.yml
.gitignore
HISTORY.rst
azure-pipelines.yml
docs/userguide.rst
requirements_dev.txt
setup.cfg
setup.py
tests/common.py
tests/frameworks/test_motor_asyncio.py
tests/frameworks/test_txmongo.py
tests/test_document.py
tests/test_embedded_document.py
tests/test_fields.py
tests/test_marshmallow.py
tox.ini
umongo/abstract.py
umongo/data_proxy.py
umongo/fields.py
umongo/frameworks/motor_asyncio.py
umongo/frameworks/txmongo.py

- - feature: upgrade umongo for Python 3.12 compatibility
- Upgrade pymongo to >=4.6 to support Python 3.12
- Replace deprecated Motor cursor APIs: next_object() and fetch_next → async for / next()
- Replace deprecated asyncio.get_event_loop() with new event loop fixture
- Remove or fix other Python 3.12 incompatibilities and deprecation warnings
- Replaced deprecated marshmallow missing with load_default / dump_default
- Updated asyncio usage:
- Replaced asyncio.coroutine with asyncio.iscoroutinefunction + async wrappers
- Migrated validator runner to asyncio.gather
- Fixed txmongo dict_items TypeError by casting to list before sort
- Updated MotorAsyncIO integration:
- Conditional import of motor with pytest skip markers if missing
- Adjusted test cases for default handling and async …

feat: upgrade umongo for Python 3.12 compatibility
